####################################################################################################
# Import
####################################################################################################

import os
import subprocess
import sys

####################################################################################################
# Constant
####################################################################################################

APPLICATION_FILES = [
    "../../../Eclectic/Data/list.c",
    "../../../Eclectic/Miscellaneous/memory.c",
    "../../../Eclectic/FSM/fsm.c",
    "main.c",
    "traffic.c"
]
APPLICATION_DEFINES = [
    "-D_DEFAULT_SOURCE"
]
APPLICATION_FLAGS = [
    "-std=c17",
    "-Weverything",
    "-Wno-covered-switch-default",
    "-Wno-padded"
]
APPLICATION_INCLUDE_PATHS = [
	"-I../../..",
    "-I."
]
APPLICATION_LIBRARIES = [
    "-lncurses"
]
BUILD_DIRECTORY = "Build"
COMPILER = "clang"
LIBRARY_FILES = [
]
LIBRARY_DEFINES = [
]
LIBRARY_FLAGS = [
]
LIBRARY_INCLUDE_PATHS = [
]
PROJECT_NAME = "Demo"

####################################################################################################
# Function
####################################################################################################

def get_file_rule(build_directory, compiler, defines, flags, include_paths, file):
    # Get File Rule
    command = [compiler] + defines + flags + include_paths + ["-MM", file]
    result = subprocess.run(command, stderr=subprocess.STDOUT, stdout=subprocess.PIPE, text=True)
    if result.returncode != 0:
        print(f"{result.stdout}", flush=True)
        sys.exit()
    rule = f"{build_directory}/{result.stdout}"
    rule += f"\t@echo Compile: {os.path.basename(file)}\n"
    rule += f"\t@{compiler} {' '.join(defines)} {' '.join(flags)} {' '.join(include_paths)} -c {file} -o $@\n"
    return rule

####################################################################################################
# Program Start
####################################################################################################

# Create Makefile
with open("Makefile", "w") as makefile:
    # Header
    makefile.write("# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT!\n")
    
    # All
    makefile.write(f"all: {BUILD_DIRECTORY}/{PROJECT_NAME}.exe\n")
    makefile.write(f"\t@echo Run: {BUILD_DIRECTORY}/{PROJECT_NAME}.exe\n")
    makefile.write("\t@echo\n")
    makefile.write(f"\t@./{BUILD_DIRECTORY}/{PROJECT_NAME}.exe\n")
    
    # Executable
    o_files = " ".join([f"{BUILD_DIRECTORY}/" + os.path.splitext(os.path.basename(file))[0] + ".o" for file in (APPLICATION_FILES + LIBRARY_FILES)])
    makefile.write(f"{BUILD_DIRECTORY}/{PROJECT_NAME}.exe: {BUILD_DIRECTORY}/ {o_files}\n")
    makefile.write(f"\t@echo Link: {PROJECT_NAME}.exe\n")
    makefile.write(f"\t@{COMPILER} {BUILD_DIRECTORY}/*.o {' '.join(APPLICATION_LIBRARIES)} -o {BUILD_DIRECTORY}/{PROJECT_NAME}.exe\n")
    
    # Build Directory
    makefile.write(f"{BUILD_DIRECTORY}/:\n")
    makefile.write(f"\t@echo Create: {BUILD_DIRECTORY}/\n")
    makefile.write(f"\t@mkdir {BUILD_DIRECTORY}/\n")
    
    # File
    for file in APPLICATION_FILES:
        rule = get_file_rule(BUILD_DIRECTORY, COMPILER, APPLICATION_DEFINES, APPLICATION_FLAGS, APPLICATION_INCLUDE_PATHS, file)
        makefile.write(f"{rule}")
    for file in LIBRARY_FILES:
        rule = get_file_rule(BUILD_DIRECTORY, COMPILER, LIBRARY_DEFINES, LIBRARY_FLAGS, LIBRARY_INCLUDE_PATHS, file)
        makefile.write(f"{rule}")
    
    # Clean
    makefile.write("clean:\n")
    makefile.write("\t@echo Clean\n")
    makefile.write(f"\t@rm -fr {BUILD_DIRECTORY}\n")
