:cmock:
  :enforce_strict_ordering: TRUE
  :mock_prefix: mock_
  :plugins:
    - :ignore
  :treat_externs: :include
  :when_no_prototypes: :error

:defines:
  :test:
    - CEEDLING

:extension:
  :executable: .exe

:gcov:
  :gcovr:
    :html_medium_threshold: 50
    :html_high_threshold: 100
  :reports:
    - HtmlDetailed
  :utilities:
    - gcovr

:paths:
  :source:
    - src/**
  :test:
    - test/**

:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - gcov
    - junit_tests_report
    - stdout_pretty_tests_report
    - warnings_report

:project:
  :build_root: build
  :ceedling_version: 0.31.1
  :test_file_prefix: test_
  :which_ceedling: vendor/ceedling

:unity:
  :defines:
    - UNITY_INCLUDE_DOUBLE
