#!/bin/bash

# Ceedling
clear
ceedling clean clobber gcov:all

# Valgrind
mkdir -p ../Build/Ceedling/artifacts/valgrind/
for executable in ../Build/Ceedling/gcov/out/*/*.exe; do
  filename=$(basename -- "${executable}")
  valgrind --leak-check=full                                                           \
           --log-file=../Build/Ceedling/artifacts/valgrind/"${filename%.*}"_memory_leak_report.txt \
           --show-error-list=yes                                                       \
           --show-leak-kinds=all                                                       \
           --track-origins=yes                                                         \
           ${executable}
done
memory_leak_report=$(grep --files-without-match 'All heap blocks were freed -- no leaks are possible' ../Build/Ceedling/artifacts/valgrind/*_memory_leak_report.txt)
echo; echo Memory Leak Report:;
if [ "${#memory_leak_report}" -eq 0 ]; then
  echo "  None"
else
  for report in $memory_leak_report; do
    echo "  ${report}"
  done
fi
