:cmock:
  :enforce_strict_ordering: TRUE
  :mock_prefix: mock_
  :plugins:
    - :expect_any_args
  :treat_externs: :include
  :when_no_prototypes: :error

:defines:
  :test:
    - CEEDLING

:extension:
  :executable: .exe

:gcov:
  :html_report_type: detailed
  :gcovr:
    :report_root: ./
    :report_include:
      - ../Eclectic/CRC/
      - ../Eclectic/Data/
      - ../Eclectic/Miscellaneous/
  :reports:
    - Cobertura
    - HtmlDetailed
  :utilities:
    - gcovr

:paths:
  :test:
    - +:./**
  :source:
    - ../Eclectic/CRC
    - ../Eclectic/Data
    - ../Eclectic/Miscellaneous
  :include:
    - ../
    - ../Eclectic/CRC
    - ../Eclectic/Data
    - ../Eclectic/Miscellaneous

:plugins:
  :enabled:
    - gcov
    - report_build_warnings_log
    - report_tests_log_factory
    - report_tests_pretty_stdout

:project:
  :build_root: ./Build/
  :ceedling_version: 0.31.1
  :test_file_prefix: test_
  :which_ceedling: gem

:report_tests_log_factory:
  :reports:
    - junit
