name: Eclectic

on:
  pull_request:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Build And Test
        run: |
          sudo gem install ceedling
          pip install gcovr
          ./ceedling
      - name: Artifact Upload
        uses: actions/upload-artifact@v4
        with:
          path: build/artifacts/gcov/*
