name: Eclectic

on:
  pull_request:
  push:

jobs:
  test:
    name: Test
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
      - name: Build And Test
        run: |
          sudo apt install valgrind
          sudo gem install ceedling
          pip install gcovr
          chmod +x ceedling
          ./ceedling
        working-directory: ./Ceedling/
      - name: Test Report
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          include_passed: true
          report_paths: ./Ceedling/Build/artifacts/gcov/junit_tests_report.xml
      - name: Coverage
        uses: 5monkeys/cobertura-action@master
        with:
          minimum_coverage: 90
          path: ./Ceedling/Build/artifacts/gcov/gcovr/GcovCoverageCobertura.xml
          skip_covered: false
